# Generated by Django 6.0.2 on 2026-04-01 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Час, День, Абонемент', max_length=100, verbose_name='Название тарифа')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (в рублях)')),
                ('description', models.CharField(help_text='Краткое описание тарифа', max_length=200, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Чем меньше число, тем выше карточка', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли тариф на сайте', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
