# Generated by Django 6.0.2 on 2026-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('coffee', 'Кофе'), ('desserts', 'Десерты'), ('author', 'Авторские напитки')], default='coffee', max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('ingredients', models.CharField(blank=True, max_length=300, verbose_name='Ингредиенты')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('badge', models.CharField(blank=True, max_length=50, null=True, verbose_name='Значок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Позиция меню',
                'verbose_name_plural': 'Позиции меню',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_text', models.CharField(default='Действует доставка от 500₽', max_length=200, verbose_name='Текст доставки')),
                ('footer_quote', models.CharField(default='"Ваш любимый кофе ждет вас"', max_length=200, verbose_name='Цитата')),
                ('page_title', models.CharField(default='Меню - Уютная кофейня', max_length=200, verbose_name='Заголовок страницы')),
            ],
            options={
                'verbose_name': 'Настройки меню',
                'verbose_name_plural': 'Настройки меню',
            },
        ),
    ]
